# Generated by Django 3.2.8 on 2021-10-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('BR', 'Breakfast'), ('SR', 'Starter'), ('MN', 'Main'), ('SD', 'Side'), ('DS', 'Dessert'), ('BK', 'Bakes'), ('SL', 'Salad'), ('SP', 'Soup')], default='MN', max_length=2),
        ),
    ]
