# Generated by Django 3.2.8 on 2021-10-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('VV', 'Vegan'), ('F', 'Fish')], default='Vegetarian', max_length=15),
        ),
    ]
