# Generated by Django 3.2.8 on 2021-10-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_recipe_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Starter', 'Starter'), ('Main', 'Main'), ('Salad', 'Side'), ('Dessert', 'Dessert'), ('Bakes', 'Bakes'), ('Salad', 'Salad'), ('Soup', 'Soup')], default='Main', max_length=15),
        ),
    ]
